module gpu_video_fpga_top #(
    parameter int H_ACTIVE = 640,
    parameter int H_FRONT = 16,
    parameter int H_SYNC = 96,
    parameter int H_BACK = 48,
    parameter int V_ACTIVE = 480,
    parameter int V_FRONT = 10,
    parameter int V_SYNC = 2,
    parameter int V_BACK = 33,
    parameter bit HSYNC_ACTIVE = 1'b0,
    parameter bit VSYNC_ACTIVE = 1'b0,
    parameter int COORD_W = 12,
    parameter int CHECKER_SHIFT = 4,
    parameter int ADDR_W = 32,
    parameter int DATA_W = 32,
    parameter int DEPTH_WORDS = 1024,
    parameter int GPU_PC_W = 8,
    parameter int GPU_LANES = 4,
    parameter int GPU_REGS = 16,
    parameter int GPU_INSTR_W = 32
) (
    input logic clk,
    input logic rst_n,
    input logic [3:0] sw,
    input logic [1:0] btn,

    output logic hsync,
    output logic vsync,
    output logic [4:0] vga_r,
    output logic [5:0] vga_g,
    output logic [4:0] vga_b,
    output logic active,
    output logic frame_start,
    output logic gpu_busy,
    output logic [7:0] gpu_error_status
);
    localparam int FIFO_DEPTH = 4;
    localparam int FIFO_COUNT_W = $clog2(FIFO_DEPTH + 1);
    localparam logic [ADDR_W-1:0] FB_BASE = '0;
    localparam logic [ADDR_W-1:0] STRIDE_BYTES = ADDR_W'(H_ACTIVE * 2);

    logic [15:0] rgb;

    assign vga_r = active ? rgb[15:11] : 5'b0;
    assign vga_g = active ? rgb[10:5] : 6'b0;
    assign vga_b = active ? rgb[4:0] : 5'b0;

    gpu_video_controller_system #(
        .H_ACTIVE(H_ACTIVE),
        .H_FRONT(H_FRONT),
        .H_SYNC(H_SYNC),
        .H_BACK(H_BACK),
        .V_ACTIVE(V_ACTIVE),
        .V_FRONT(V_FRONT),
        .V_SYNC(V_SYNC),
        .V_BACK(V_BACK),
        .HSYNC_ACTIVE(HSYNC_ACTIVE),
        .VSYNC_ACTIVE(VSYNC_ACTIVE),
        .COORD_W(COORD_W),
        .ADDR_W(ADDR_W),
        .DATA_W(DATA_W),
        .FIFO_DEPTH(FIFO_DEPTH),
        .FIFO_COUNT_W(FIFO_COUNT_W),
        .CHECKER_SHIFT(CHECKER_SHIFT),
        .DEPTH_WORDS(DEPTH_WORDS),
        .GPU_FB_WIDTH(H_ACTIVE),
        .GPU_FB_HEIGHT(V_ACTIVE),
        .GPU_PC_W(GPU_PC_W),
        .GPU_REGS(GPU_REGS),
        .GPU_LANES(GPU_LANES),
        .GPU_INSTR_W(GPU_INSTR_W),
        .FRONT_BASE_RESET(FB_BASE),
        .BACK_BASE_RESET(FB_BASE)
    ) system (
        .clk(clk),
        .rst_n(rst_n),
        .memory_req_stall(1'b0),
        .gpu_enable(1'b1),
        .gpu_clear_errors(btn[0]),
        .cmd_valid(1'b0),
        .cmd_ready(),
        .cmd_data('0),
        .imem_write_en(1'b0),
        .imem_write_addr('0),
        .imem_write_data('0),
        .gpu_busy(gpu_busy),
        .gpu_error_status(gpu_error_status),
        .tick_enable(1'b1),
        .source_select(sw[0]),
        .pattern_select(sw[2:1]),
        .solid_rgb(sw[3] ? 16'hffff : 16'h07e0),
        .scanout_start_valid(btn[1]),
        .scanout_start_ready(),
        .fb_base(FB_BASE),
        .stride_bytes(STRIDE_BYTES),
        .fifo_flush(btn[0]),
        .swap_enable(1'b0),
        .swap_request(1'b0),
        .swap_ready(),
        .swap_pending(),
        .swap_pulse(),
        .swap_front_base(),
        .swap_back_base(),
        .scanout_busy(),
        .scanout_done(),
        .scanout_error(),
        .fifo_full(),
        .fifo_empty(),
        .fifo_count(),
        .fifo_overflow(),
        .fifo_underflow(),
        .framebuffer_underrun(),
        .framebuffer_coordinate_mismatch(),
        .source_missing(),
        .pixel_valid(),
        .active(active),
        .line_start(),
        .frame_start(frame_start),
        .hsync(hsync),
        .vsync(vsync),
        .x(),
        .y(),
        .rgb(rgb),
        .debug_gpu_mem_req_valid(),
        .debug_video_mem_req_valid(),
        .debug_gpu_mem_req_fire(),
        .debug_video_mem_req_fire()
    );
endmodule
